#!/bin/sh /etc/rc.common
# OpenWrt rc.common consumes these service metadata variables.
# shellcheck disable=SC2034

START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/zte-usb-wifi-managerd
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger zte-usb-wifi-manager
}

reload_service() {
	stop
	start
}
