include $(TOPDIR)/rules.mk

PKG_VERSION:=0.1.0_rc1
PKG_RELEASE:=11
PKG_LICENSE:=MIT
PKG_MAINTAINER:=caixy-plus

LUCI_TITLE:=LuCI support for ZTE USB WiFi Manager
LUCI_DEPENDS:=+zte-usb-wifi-manager
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
